### ISSUE TITLE
Github Repo Separation

### ISSUE THREAD

**Issue by AchmadFathoni** [acxz/pkgbuilds#131]
Every AUR in this repo should be separated to individual repo. So people don't need to have 2 copy of same AUR in their machine. Also this repo's issue & PR page are cluttered with issue & PR from different AUR. 

This is my current workflow.

1. Get broken upstream AUR in `~/.cache/yay/orocos-kdl-python`
2. Fix it
3. Pull `~/pkgbuilds/orocos-kdl-python`
4. Copy .SRCINFO and PKGBUILD to `pkgbuilds/orocos-kdl-python`
5. Commit, push, and make PR

If you separate each AUR to individual repo, the workflow will be much easier

1. Get broken upstream AUR in `~/.cache/yay/orocos-kdl-python`
2. Fix it
3. Run ` git remote add github git@github.com:AchmadFathoni/orocos-kdl-python.git ` once.
4. Commit, push and make PR

What is your workflow @acxz? And what is the reason for making one Github repo for multiple AUR?

**Comment by acxz** [comment]
My workflow for this repo is based on using [`aurpublish`](https://github.com/eli-schwartz/aurpublish).
Instead of having a repo for each package, it is much easier to have one repo for all my packages.
One downside is that based on how many packages I have, it is the `.git` can get pretty big.

There may be a way to directly add the subtree as a remote, although I am not familiar enough with git subtrees.

I am not going to split my packages that I maintain into separate repos.
