### ISSUE TITLE
[gazebo-git] Fails to build

### ISSUE THREAD

**Issue by bobosito000** [acxz/pkgbuilds#164]
1. Depends list is outdated.
2. There's an issue compiling from source with tbb2020 and boost.

**Comment by acxz** [comment]
1. I have made the PKGBUILD more inline with the `gazebo` package.
2. Since this is a `git` packages please report compilation issues to the official repository. This package only recreates a build process, it is not a release package and as such I don't think it is proper to patch these issues. Once they are fixed in the upstream repo they will be immediately available here.
