### ISSUE TITLE
[python-pyqt5-sip4] Build error

### ISSUE THREAD

**Issue by AchmadFathoni** [acxz/pkgbuilds#175]
```
Traceback (most recent call last):
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.5.1', 'console_scripts', 'sip-build')())
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Comment by acxz** [comment]
Can you try building in a chroot? It could be something wrong with your local environment.

I'd recommend using paru --chroot.

**Comment by AchmadFathoni** [comment]
Thanks, I guess it fixed.

**Comment by acxz** [comment]
Hey all sorry for troubles with this package, I hate that it exists, and I hate how it works (to build it), but it is a necessary evil until things get properly fixed (which they will not) so for everyone that cares about robots on archlinux and needs to use this package these are my tidbits on building this package:

1) Build in a clean chroot:

This is the proper way, all packages should be built in a clean chroot anyway.
The traditional method to do this is to use the method as described by @FabioLolix in his comment [here](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)

If you want better tooling use `paru`'s `--chroot` flag. (I'll let you look up how to do this on your own using `paru`'s docs) I personally use this option.

2) Use [arch4edu](https://github.com/arch4edu/arch4edu)!

Why build packages when they are already built for you! See their github page for how to get setup with it. (Give a star on your way there they deserve it, they (he is a one man team) has been hosting robotics packages for a long long time (we go back))

3) Build without using a clean chroot

This one is trickiest.
- Make sure `sip4` is uninstalled and `sip` is installed.
- Build this package (keeping in mind you aren't using too many cores, since this package eats RAM like my wife eating chocolate)
- Uninstall `sip`
   - This is to make sure that when you install subsequent packages that depend on `sip4`, you won't get dep conflicts with `sip`
- Continue along your merry way

Hopefully that was complete enough for everyone. If you are still having issues with any one of these methods feel free to comment on here.

**Comment by MoRoBe-Work** [comment]
For reference: I had the error `/var/tmp/pamac-build-***/python-pyqt5-sip4/PKGBUILD: line 53: sip-build: command not found` when trying to install python-pyqt5-sip4 package from the AUR. The arch4edu package works like a charm and includes multiple additional robotics packages I use in newer versions. Thank you for the recommendation!
