### ISSUE TITLE
[python-pyqt5-sip4] Installation causes system shutdown

### ISSUE THREAD

**Issue by sokoloowski** [acxz/pkgbuilds#241]
While installing package, Manjaro (22.1.1 with KDE Plasma) shutted down. After reboot I've tried installing it again, but with saving console output to file. It fails on generating Qt bindings:

![first-attempt](https://github.com/acxz/pkgbuilds/assets/39133910/01bfe4ce-2564-4b1c-ad89-d91aaef176f5)

Initially I've tried to install it with `yay`, next try was with `paru`, but with the same effects.

After few more attempts, it went through, but caused a system halt after some logs from `g++`:

![another-attempt](https://github.com/acxz/pkgbuilds/assets/39133910/48cda43a-1fb8-4ed6-9b91-a41a2315437f)

Log from the last attempt: https://pastebin.com/pFELHRZH

**Comment by acxz** [comment]
Hello @sokoloowski thanks for the report! Sorry for the late response.
In the future (any for any bug reporting) please use text instead of images for your logs so that search engines and users can easily search through via `Ctrl-F`. (yes I know you put a pastebin which I appreciated, but still no images plz)

Also Manjaro is not supported.

Okay getting those nits out of the way, your issue is most likely you don't have enough system ram to build this package. You can use an already precompiled build of this package hosted on https://github.com/arch4edu/arch4edu or you can try to build it yourself again and make sure you are only specifying a single core for your `MAKEFLAGS` in your `/etc/makepkg.conf` (i.e the line should read `MAKEFLAGS="-j1"`.

I'm gonna close this issue for now, but you have any more issues or concerns please feel free to comment.
